In [46]:
#1创建一个长度为10的一维全为0的ndarray对象，然后第五个元素等于1。
# import numpy as np
# x=np.array([0,0,0,0,1,0,0,0,0,0])
# print(x)
x=np.zeros([1,10],dtype = int)
x[0,4]=1
print(x)

[[0 0 0 0 1 0 0 0 0 0]]


In [37]:
#2创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积
import numpy as np
x = np.empty([5,3],dtype = int)
print(x)
print('\n')
j = np.empty([3,2],dtype = int)
print(j)
print('\n')
print(np.dot(x,j))

[[ 0  3  6]
 [ 9 12  1]
 [ 4  7 10]
 [13  2  5]
 [ 8 11 14]]


[[     93939023177872      93939018617760]
 [                  0                   0]
 [7291389589298756130 3688560464807145527]]


[[ 6854849388373433548  3684618715133321546]
 [ 7292235040507356978  3689405915974705367]
 [ -872704645757933676    -7507743273176922]
 [ -435318993624010246    -2720542431793101]
 [-8600258679889300900 -3699634201679675390]]


In [60]:
#3冒泡排序法
a = np.array([[12,33,35],[3,54,23]])
temp=a.flatten('F')
temp.sort()
print(temp)

[ 3 12 23 33 35 54]


In [66]:
#4找到数组【1，2，0，0，4，0】中0元素的位置索引
a = np.array([1,2,0,0,4,0])
i1=0
for i in a:
    i1+=1
    if i == 0:
        print(i1-1)


2
3
5


In [83]:
#5创建一个 10x10 的随机数组并找到最大值和最小值
a = np.empty([10,10],dtype = int)
print(a)
b = np.concatenate(a)
print("最大值:",b.max())
print("最小值:",b.min())

[[                  0                   0                  -1
                    0 2314885616178823169                   0
                    9     140314769743058      93939020680060
                   -1]
 [                  0                  -1                   0
  2314885530279477249                  72                  11
      140314769743058      93939020680560                   3
                   28]
 [                 -1                   0 2314885598998953985
                  144                  11     140314769743058
       93939020680576                   2                  32
                   -1]
 [                  0 3545230331567144961                 216
                   11     140314769743058      93939020680584
                    0                  32                  -1
                   10]
 [3472898976313769985                 288                   8
      140314769743060      93939020682744                   0
                   16                  -

In [85]:
#6求解方程
# 3x1+3.2x2 = 118.4
# 3.5x1+3.6x2 = 135.2
a = np.array([[3,3.2],[3.5,3.6]])
b = np.array([118.4,135.2])
print(a,'\n')
print(b,'\n')
c = linalg.inv(a)
e = dot(c,b)
print(e)

[[3.  3.2]
 [3.5 3.6]] 

[118.4 135.2] 

[16. 22.]
